spring:
  application:
    name: detectives-service # Service registers under this name
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password:

    jpa:
      database: mysql
      generate-ddl: true
      hibernate.ddl-auto: create-drop

# HTTP Server
server:
  port: 4002   # HTTP (Tomcat) port
  address: 0.0.0.0

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/


  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: false

info:
  app:
    name: detectives-server
    description: Spring Cloud Application Managing Detectives Instances
    version: 1.0-SNAPSHOT

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.cloud.: DEBUG
